### ISSUE TITLE
Visible folder support within collections

### ISSUE THREAD

**Issue by bezza191** [mmatyas/pegasus-frontend#1080]
Would it be possible to implement visible subfolders within a given collection, similar to how Emulation Station shows them?

Pegasus already scans subdirectories but then all files are in one list, where as allowing for visible folders would allow for additional organisation within an existing system

For example, having the standard SNES collection defined and within the collection a "Hacks" or "Translated" subdirectory

Image included as a visual example

![IMG_2243](https://github.com/mmatyas/pegasus-frontend/assets/37932350/a142beed-c007-43e5-a276-71950248a80f)

**Comment by mmatyas** [comment]
I'm not against the idea, but at the moment it's not really how Pegasus works. ES has distinct systems, while Pegasus has collections, where a single game can appear in multiple collections.

We could then probably assume that different collections might have different folders too. So for each game we would need to tell in the metadata file the list of subfolders it belongs to in the different collections. We would also need to figure out themeing, as instead of a plain list, the collections would be "directory trees".

**Comment by bezza191** [comment]
That's fair enough, I see your point

thanks for taking the time to respond. I'll close this out.
