### ISSUE TITLE
Create a Debian package for easy installation

### ISSUE THREAD

**Issue by AlexandreBonneau** [mmatyas/pegasus-frontend#202]
Nice work on the front-end!

It would be great if a Debian package could be built and uploaded on the official repo.

**Comment by mmatyas** [comment]
Thanks! Unfortunately though some assets, like game system logos, are under Creative Commons noncommercial license, which is -as far as I know- against the Debian package policy. I also tend to use more recent versions of Qt that's available from the repos, so a regular build would likely require the `experimental` channel. A third-party PPA could be set up, however.

**Comment by mmatyas** [comment]
I've set up a Debian repo, you can try it like this:

```sh
# Add the repository
curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
sudo add-apt-repository 'deb https://dl.bintray.com/mmatyas/deb testing main'

# Update and install
sudo apt update
sudo apt install pegasus-frontend
```

**Comment by mmatyas** [comment]
I'm closing the issue, but feel free to report if you get any problems.

**Comment by AlexandreBonneau** [comment]
This works great, thanks!

**Comment by j8r** [comment]
I don't know if you noticed https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ @mmatyas, Bintray is going to shutdown. I propose Open Build Service (OBS) as an alternative: https://en.opensuse.org/Portal:Build_Service.

**Comment by mmatyas** [comment]
Thanks for the info! Indeed these news have managed to escape me somehow. The problem I had with OBS is that it [requires all sources to be built on site](https://en.opensuse.org/openSUSE:Packaging_guidelines#No_inclusion_of_pre-built_binaries_or_libraries). Because both Ubuntu and Debian ship with ancient versions of Qt, I have to build Qt manually; if I have to recompile it every time, that'd increase the build time *by hours*. I'm not sure if they even grant that much server time.

Since there's already a working build system, the best solution for me would be a simple site where I can just upload a plain DEB file -- like Bintray.

**Comment by j8r** [comment]
Isn't possible to statically compile Pegasus?

**Comment by mmatyas** [comment]
Yes, that's what we have now.

**Comment by j8r** [comment]
So, I don't really understand what's the problem: the package is built with sources, as usual. But then, instead of having the non-dev(el) versions of this libraries as dependencies, which are dynamically-linked, it has none. Not possible with OBS?

**Comment by mmatyas** [comment]
In theory, we can either link dynamically to the Qt libs of the system, or build Qt manually and ship it as part of Pegasus.

In practice, we can't use the first option because the distro's libs are too old. We also cannot use the second option with OBS (or any other service), because building Qt takes too much time. The solution we have currently is that the Qt build is cached, and later reused for the following builds. However, as far as I know this is not allowed on OBS.

**Comment by j8r** [comment]
I think it is fine to have multiple hours builds if they are not done multiple times per day.

**Comment by j8r** [comment]
What about creating a [PPA on Launchpad](https://launchpad.net/+tour/ppa)?

**Comment by mmatyas** [comment]
As far as I know, Launchpad also has a no-binary policy.

**Comment by j8r** [comment]
I'd like to remove the bintray deb section from https://pegasus-frontend.org/#downloads, but having found the source of the site published in [gh-pages](https://github.com/mmatyas/pegasus-frontend/tree/gh-pages).

**Comment by mmatyas** [comment]
Yea, looks like Bintray is dead now. I've removed the APT section.

**Comment by mmatyas** [comment]
Closing for now, as the original issue is solved, ie. we have Debian packages, what we don't have are APT repositories. If someone wants to maintain one, feel free to do it! (Note that we also have Flatpak for a Linux release channel as well.)
