### ISSUE TITLE
Feature Request: Background music with keys for next, prev, off

### ISSUE THREAD

**Issue by bleuge** [mmatyas/pegasus-frontend#468]
Maybe you like this idea, able to play music (mp3 only is perfect, but possibly you could play many more formats with the library) in the background. 

This could be a nice jukebox, add keys for next, prev, etc (maybe some options in settings, as random play). And we could have arcade ambiances in the background, or just plain music.
Fading out a bit when playing a video would be perfect. Music could be in a folder called music, or whatever.

Regards!

**Comment by mmatyas** [comment]
Hi, all these can be done by themes, the music/sound playback is fully supported by Pegasus itself. Now as for the default theme, it got a bit too loaded with features and issues since the beginning of the development, so I'd rather not anything more for now until it's in a better shape. I do would like to see something like this in the future though!

**Comment by bleuge** [comment]
great! thanks!
