### ISSUE TITLE
Update API reference in theme tutorials

### ISSUE THREAD

**Issue by tobiasger** [mmatyas/pegasus-frontend#470]
First off I just want to say that the theme tutorials are very detailed and educative! Kudos for that!

Would it be possible to get an update regarding the changed API reference in the theme creation tutorials? I've tried to figure out what the differences are with the updated API, but it feels like some of the new practices aren't explained. I'm especially having trouble with changing and getting the current index of the collections and games.

**Comment by mmatyas** [comment]
Thanks! Yes, they were written quite a while ago, so I'd like to update them eventually (and maybe extend with QML tutorial chapters), just haven't had the time yet. I've wrote a list of the differences [here](https://retropie.org.uk/forum/post/170963), in short because the lists can appear on multiple places, the indices are not maintained on the API anymore, but on the QML side (which makes storing them a bit more difficult, but I'll see if it can be improved).

**Comment by tobiasger** [comment]
Thank you very much! That list of differences is very helpful. Maybe it should be mentioned in the theme documentation until it’s been updated?

Either way, didn’t mean to stress you, just thought it was worth asking for an update. :)

**Comment by mmatyas** [comment]
Ah now that you mention it, I just recalled there's a link to it [here](https://pegasus-frontend.org/docs/user-guide/breaking-changes/) at the bottom. So yeah, that'd be indeed a good idea to make it more visible :)

**Comment by mmatyas** [comment]
If I remember correctly, I've updated the documentation since then everywhere, so I think this can be closed now. Feel free to report if there are still issues in them!
