### ISSUE TITLE
Launching Windows Apps

### ISSUE THREAD

**Issue by RexBorova** [mmatyas/pegasus-frontend#471]
Not necessarily an issue, but was curious if I was able to manually launch Windows applications with Pegasus, like it's Android counterpart? Windows OS has (pardon my French) a fucking shitty 10 foot user interface, as in almost non existent.

I'm on Win10 if that helps in any way.

**Comment by mmatyas** [comment]
Yes, you can launch EXE files without problems, in this case the launch command would be
```
launch: {file.path}
```

**Comment by RexBorova** [comment]
That's awesome. Thank you. Can the file path be linked to shortcuts or does it need to be to the actual file path of the program?

**Comment by mmatyas** [comment]
I'm not sure Windows allows that, but it's certainly worth a try! According to some articles, it might need to be called as `start {file.path}`, but I haven't tried yet whether it works.

**Comment by RexBorova** [comment]
Alrighty I'll give it a shot too. I've tried a few things today and maybe I did (a lot) wrong but these are what I was able to produce.

- Made a collection in the root of a .exe folder (PS$ remote PLay in this example) with the following,

**collection: Windows 10
extensions: exe
launch: "{file.path}"**

Shows up in Pegasus and able  to launch application.

- Made a collection in a separate folder with the a couple of shortcut to applications with the following,

**collection: Windows 10
extensions: lnk
launch: "{file.path}"**

They show up in Pegasus but none of the applications launch. Strangest part is that i made a shortcut for the Xbox Companion App in the same folder, and that doesn't show up at all, which is my main focus for this.

Not sure what I'm doing wrong, but thanks again for your help!

**Comment by PlayingKarrde** [comment]
Just reviving this thread again due to the LaunchBox integration and subsequent issues. 

I'm unable to launch links also, and I noticed that if there are relative paths in the launchbox launcher application path, it gives the same error for exes as well (LB unfortunately adds relative paths by default :(). May also have something to do with the working path dir but unsure on that.

Anyway just throwing new (?) information out there.

**Comment by PlayingKarrde** [comment]
[Here's a pastebin of my latest](https://pastebin.com/54pwKeRV). Pegasus isn't picking up any of the links I'm adding manually. Annoyingly it is importing relative paths, but even if I set it manually (as you can see with the Gears 5 link) it still doesn't find it. Strange.

I'm assuming since you don't have a Windows machine it would be very difficult to detect installed Xbox/Microsoft Store games like Steam, but if that were possible that would be amazing.

**Comment by mmatyas** [comment]
Did some tests and I can now confirm shortcuts don't work at the moment. Tried different different ways, like the lnk in itself, via `cmd` and also with `explorer`, but none of them were working well. `explorer {file.path}` *sometimes* worked, but most of the time just opened the file manager.

I've checked the source code of .Net but it doesn't seem to do anything special either. This seems to be a Qt bug.

**Comment by mmatyas** [comment]
Also feel free to open new issues for any *other* issues :)

@PlayingKarrde relative paths shouldn't be a problem, they are just printed as the to the log. I've made it print the full path now in the latest version.

@PlayingKarrde I'm still on Windows 7 personally. I think it should be possible to query the MS Store games, but I'm not sure what kind of metadata is available for them.

**Comment by mmatyas** [comment]
Ok, shortcut launching too should now work in the latest version!
