### ISSUE TITLE
Hide Desktop when loading emulator

### ISSUE THREAD

**Issue by QcGix** [mmatyas/pegasus-frontend#473]
Hi,

I've just installed Pegasus on Windows 10 and I was wondering if it's possible to hide the desktop after you choose a game. When I click on a game it show the desktop for a second then load the emulator. Front End like Launchbox put a full screen loading image so the desktop is hidden and it give a clean experience. I saw that it's possible to script event on game-start and game-end but I'm not sure what would be the best approach (full screen image?).

Thanks! (Awesome Front End!)

**Comment by mmatyas** [comment]
Hi, and sorry for the late reply! Pegasus closes as soon as the emulator says "I've started!". Unfortunately many programs report that even before they've drawn anything to the screen. It cannot be decided whether this is intentional (eg. because the program is a command line application) or just the program being slow. Because on certain systems only one program can be present on the screen at a time, Pegasus closes as soon as the emulator reports that it started to avoid problems. As for other systems, there's no loading image support yet, but would be nice to add something like this. Until then, perhaps opening a simple black image fullscreen, before Pegasus starts, could help (I think eg. IrfanView has such an option).

**Comment by QcGix** [comment]
I will try a full screen black image in IrfanView. Thanks!
