### ISSUE TITLE
libpng warning... what's the warning explanation?

### ISSUE THREAD

**Issue by fastpop72** [mmatyas/pegasus-frontend#484]
I have several of these warning messages on the log... what are related to??

2019-07-29T13:00:39 [w] libpng warning: iCCP: known incorrect sRGB profile
2019-07-29T13:00:39 [w] libpng warning: iCCP: cHRM chunk does not match sRGB

Thanks!

**Comment by mmatyas** [comment]
Hi, in short, these are harmless warnings saying that the software that created the PNG file has added some additional information to the file that isn't entirely correct. Maybe it was made with some older Photoshop, or was downloaded from a site which changed the image. It shouldn't cause any problems though.

In longer:

For accurately producing colors in a device-independent way, PNG files can optionally contain colorspace information blocks for various standards. These are `cHRM` (1931 CIE x,y chromaticities), `sRGB` (standard RGB) and `iCCP` (profile defined by the International Color Consortium, a more verbose form of `sRGB`). A file can have more than one in it to increase compatibility. Profiles have a well defined values, like `sRGB_IEC61966` or `sRGB_v4_ICC`, issued mainly by manufacturers and standard bodies, it seems. Now during the years it turned out some of them were defined incorrectly, like incorrect luminance settings (eg. `HP-Microsoft sRGB v2 1998`), which can produce side effects where high precision is needed. The PNG loading library has a list of such profiles and prints a warning when it sees them in a file. For most common images, ignoring the incorrect color profile shouldn't have any visible effects (especially if it has other profiles to fall back in the file). If you're concerned though, you can always open it in some image editor and save the file again (may involve toggling a few settings).

Sources: PNG Specification 1.2, libpng source code
Also I'm not an expert so these might be not 100% accurate.

**Comment by fastpop72** [comment]
These informations could it be in the metadata of the PNG files? I can remove all the metadata from them if it helps...

**Comment by mmatyas** [comment]
I think yes, they should be in the metadata section, but personally I haven't tried removing them yet.

**Comment by fastpop72** [comment]
Thank you! I will try!

**Comment by mmatyas** [comment]
Closing for now, feel free to report if you run into any issues!

**Comment by fastpop72** [comment]
Thank you. Seems that removing metadatas from the PNG works... Anyway i have a lot of warnings related to the theme i use.

I suggest to add a command line options like --no-warnings to disable these outputs in order to have a clean bash window. 

Thanks.
