### ISSUE TITLE
Metadata Converter - gamelist.xml screenshot -> boxfront; boxart ignored

### ISSUE THREAD

**Issue by romadu** [mmatyas/pegasus-frontend#949]
### The issue

My gamelist.xml files, generated by skraper, include three media files per game: `media/videos` for videos, `media/images` for screenshots, labelled as `image`, `media/boxart` for boxart, labelled as `thumbnail`. However, metadata converter only converts two media files, using media/images as `assets.boxfront`, and does not transpose an `assets.screenshot` image/category.

input
```    
<image>./media/images/Ape Escape - On the Loose (USA).png</image>
<thumbnail>./media/boxart/Ape Escape - On the Loose (USA).png</thumbnail>
<video>./media/videos/Ape Escape - On the Loose (USA).mp4</video>
```

output
```
assets.boxfront: ./media/images/Ape Escape - On the Loose (USA).png
assets.video: ./media/videos/Ape Escape - On the Loose (USA).mp4
```

Do the gamelist.xml category labels need to modified to work correctly with metadata converter?

### System info

javascript converter tool https://pegasus-frontend.org/tools/convert/

**Comment by mmatyas** [comment]
Hi, there are multiple incompatible forks of EmulationStation, and the online converter is based on the last official release of ES. According to its documentation, `thumbnail` is expected to be a smaller version of `image`, but since downscaling is handled automatically in Pegasus, there's no thumbnail-related line in the output.

If it's not important to have the asset lines in the metadata file, you can also make use of Pegasus' autodetection for assets. If the Skraper Assets provider is turned on, it will look for screenshot at `./media/screenshot`,  box front at `./media/box2dfront`, and video at `./media/videos`.

**Comment by romadu** [comment]
Thanks. I'll remove the asset lines from metadata file then.
